import cox from "./assets/Image/Rectangle 1.png";
// import SreeMangal from "./assets/Image/Sreemongol.png";
// import SundarBan from "./assets/Image/SundarBan.png";

let FakeData = [
  {
    id: "1",
    placeName: "Cox's Bazar",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi pariatur odio ut deleniti quas quaerat minus repellat earum consequatur est, corrupti dolorum veritatis obcaecati officiis?",
    hotels: [
      {
        name: "sea beach",
        guests: 4,
        beds: 2,
        rooms: 2,
        baths: 2,
        location: {
          address: "1600 Amphitheatre Parkway, Mountain View, Cox'sbazar.",
          lat: 21.4284953,
          lng: 91.9614311,
        },
        rating: "4.9",
        cost: "40",
        reviews: "123",
        imageUrl: "/images/Rectangle 26.png",
        id: 1,
      },
      {
        name: "Hotel sr",
        guests: 4,
        beds: 2,
        rooms: 2,
        baths: 2,
        location: {
          address: "1600 Amphitheatre Parkway, Mountain View, california.",
          lat: 21.4197458,
          lng: 91.979039,
        },
        rating: "4.9",
        cost: "60",
        reviews: "123",
        imageUrl: "/images/Rectangle 27.png",
        id: 2,
      },
      {
        name: "hotel Cox",
        guests: 4,
        beds: 2,
        rooms: 2,
        baths: 2,
        location: {
          address: "1600 Amphitheatre Parkway, Mountain View, california.",
          lat: 21.4149439,
          lng: 91.9799096,
        },
        rating: "4.9",
        cost: "23",
        reviews: "123",
        imageUrl: "/images/Rectangle 26.png",
        id: 3,
      },
    ],
    image: "Rectangle 1",
  },
  {
    id: "2",
    placeName: "SreeMangal",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi pariatur odio ut deleniti quas quaerat minus repellat earum consequatur est, corrupti dolorum veritatis obcaecati officiis?",
    hotels: [
      {
        name: "Oyo",
        guests: 4,
        beds: 2,
        rooms: 2,
        baths: 2,
        location: {
          address: "1600 Amphitheatre Parkway, Mountain View, california.",

          lat: 24.3030469,
          lng: 91.7238031,
        },
        rating: "4.9",
        cost: "40",
        reviews: "123",
        imageUrl: "/images/Rectangle 26.png",
        id: 1,
      },
      {
        name: "Mount everest",
        guests: 4,
        beds: 2,
        rooms: 2,
        baths: 2,
        location: {
          address: "1600 Amphitheatre Parkway, Mountain View, california.",
          lat: 24.3030469,
          lng: 91.7238031,
        },
        rating: "4.9",
        cost: "50",
        reviews: "123",
        imageUrl: "/images/Rectangle 27.png",
        id: 2,
      },
      {
        name: "hotel Sreemangal",
        guests: 4,
        beds: 2,
        rooms: 2,
        baths: 2,
        location: {
          address: "1600 Amphitheatre Parkway, Mountain View, california.",
          lat: 24.3030469,
          lng: 91.7238031,
        },
        rating: "4.9",
        cost: "90",
        reviews: "123",
        imageUrl: "/images/Rectangle 26.png",
        id: 3,
      },
    ],
    image: "Sreemongol",
  },
  {
    id: "3",
    placeName: "SundarBan",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi pariatur odio ut deleniti quas quaerat minus repellat earum consequatur est, corrupti dolorum veritatis obcaecati officiis?",
    hotels: [
      {
        name: "Beauty of Sundarban",
        guests: 4,
        beds: 2,
        rooms: 2,
        baths: 2,
        location: {
          address: "1600 Amphitheatre Parkway, Mountain View, california.",
          lat: 22.1069096,
          lng: 88.7230394,
        },
        rating: "4.9",
        cost: "80",
        reviews: "123",
        imageUrl: "/images/Rectangle 26.png",
        id: 1,
      },
      {
        name: "sundarbon delux",
        guests: 4,
        beds: 2,
        rooms: 2,
        baths: 2,
        location: {
          address: "1600 Amphitheatre Parkway, Mountain View, california.",
          lat: 22.1069096,
          lng: 88.7230394,
        },
        rating: "4.9",
        cost: "40",
        reviews: "123",
        imageUrl: "/images/Rectangle 27.png",
        id: 2,
      },
      {
        name: "Hotel sundar",
        guests: 4,
        beds: 2,
        rooms: 2,
        baths: 2,
        location: {
          address: "1600 Amphitheatre Parkway, Mountain View, california.",
          lat: 22.1069096,
          lng: 88.7230394,
        },
        rating: "4.9",
        cost: "60",
        reviews: "123",
        imageUrl: "/images/Rectangle 28.png",
        id: 3,
      },
    ],
    image: "sundorbon",
  },
];

export default FakeData;
